baseURL = "https://heathercl.gitlab.io/dsp-hugo/"
languageCode = "en-us"
title = "Syniti Documentation"
disablePathToLower = true
# enableEmoji = true
# enableRobotsTXT = true
# googleAnalytics = ("tracking number goes here")

