baseURL = "https://hcloward.github.io/"
languageCode = "en-us"
title = "Syniti Documentation"
disablePathToLower = true
# enableEmoji = true
# enableRobotsTXT = true
# googleAnalytics = ("tracking number goes here")

